"""empty message

Revision ID: 2da0fc81ddfd
Revises: a3f4b9333bf6
Create Date: 2022-06-04 12:53:53.400723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da0fc81ddfd'
down_revision = 'a3f4b9333bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'film_genres', ['film_id', 'genre_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film_genres', type_='unique')
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
