"""empty message

Revision ID: 4ae7c92ab435
Revises: f1d3fad30a7b
Create Date: 2022-05-30 09:45:00.611490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae7c92ab435'
down_revision = 'f1d3fad30a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('films_director_id_fkey', 'films', type_='foreignkey')
    op.create_foreign_key(None, 'films', 'directors', ['director_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.create_foreign_key('films_director_id_fkey', 'films', 'directors', ['director_id'], ['id'])
    # ### end Alembic commands ###
