"""empty message

Revision ID: 67b4bc9e1095
Revises: bcbf997a6f97
Create Date: 2022-06-02 23:05:39.062670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b4bc9e1095'
down_revision = 'bcbf997a6f97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
