"""empty message

Revision ID: 6bf83157d19c
Revises: a34dcd1ada2a
Create Date: 2022-05-30 09:47:46.538115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf83157d19c'
down_revision = 'a34dcd1ada2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('film_genre_film_id_fkey', 'film_genre', type_='foreignkey')
    op.create_foreign_key(None, 'film_genre', 'films', ['film_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film_genre', type_='foreignkey')
    op.create_foreign_key('film_genre_film_id_fkey', 'film_genre', 'films', ['film_id'], ['id'])
    # ### end Alembic commands ###
