"""empty message

Revision ID: 907dc34c67f2
Revises: 9e9731c98426
Create Date: 2022-05-30 09:52:14.748374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907dc34c67f2'
down_revision = '9e9731c98426'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('film_genre_genre_id_fkey', 'film_genre', type_='foreignkey')
    op.create_foreign_key(None, 'film_genre', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film_genre', type_='foreignkey')
    op.create_foreign_key('film_genre_genre_id_fkey', 'film_genre', 'genres', ['genre_id'], ['id'])
    # ### end Alembic commands ###
