"""empty message

Revision ID: a34dcd1ada2a
Revises: 4ae7c92ab435
Create Date: 2022-05-30 09:46:32.332584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34dcd1ada2a'
down_revision = '4ae7c92ab435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('films_user_id_fkey', 'films', type_='foreignkey')
    op.create_foreign_key(None, 'films', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.create_foreign_key('films_user_id_fkey', 'films', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
