"""empty message

Revision ID: a3f4b9333bf6
Revises: e21697064875
Create Date: 2022-06-03 16:53:26.591682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3f4b9333bf6'
down_revision = 'e21697064875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('film_genres_film_id_genre_id_key', 'film_genres', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('film_genres_film_id_genre_id_key', 'film_genres', ['film_id', 'genre_id'])
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
