"""empty message

Revision ID: da872c68510f
Revises: 2da0fc81ddfd
Create Date: 2022-06-19 17:19:50.665336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da872c68510f'
down_revision = '2da0fc81ddfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'premiere_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('films', 'poster_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'poster_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('films', 'premiere_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
