"""empty message

Revision ID: e21697064875
Revises: 355ff51c4ae1
Create Date: 2022-06-03 16:51:39.089292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21697064875'
down_revision = '355ff51c4ae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'film_genres', ['film_id', 'genre_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'film_genres', type_='unique')
    op.alter_column('film_genres', 'genre_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('film_genres', 'film_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
